 version: "3.9"
 services:
   frontend:
     container_name: frontend
     build:
       context: ./frontend
       dockerfile: Dockerfile
     restart: always
     env_file: .env
     ports:
       - "${FRONTEND_PORT}:${FRONTEND_PORT}"
     volumes:
       - "./frontend/src:/usr/src/app/src"
     networks:
       - transcendence
     command: "npm start"
   backend:
     container_name: backend
     build:
       context: ./backend
       dockerfile: Dockerfile
     restart: always
     env_file: .env
     volumes:
       - ./backend:/svr/app
       - "./scripts/wait.sh:/wait.sh"
       - /svr/app/node_modules
     networks:
       - transcendence
     ports:
       - "${BACKEND_PORT}:${BACKEND_PORT}"
     depends_on:
       - dev-db
     links:
       - dev-db
   dev-db:
     image: postgres:13-alpine
     restart: always
     container_name: database
     env_file:
       - .env
     environment:
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       # PGDATA: /var/lib/postgresql/data
       POSTGRES_USER: ${DB_USER}
       POSTGRES_DB: ${DB_NAME}
     ports:
       - "${DB_PORT}:${DB_PORT}"
     # volumes:
     #   - pgdata:/var/lib/postgresql/data
     networks:
       - transcendence
   pgadmin-portal:
     image: dpage/pgadmin4
     restart: always
     container_name: pgadmin-portal
     env_file:
       - .env
     environment:
       PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
       PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
     volumes:
       - pgadmin:/root/.pgadmin
     ports:
       - "${PGADMIN_PORT}:80"
     depends_on:
       - dev-db
     networks:
       - transcendence
 volumes:
   pgdata:
   pgadmin:
 networks:
   transcendence:
     driver: bridge

# services:
#   db:
#     image: postgres
#     volumes:
#     - db_data:/var/lib/postgres
#     restart: always
#     environment:
#       POSTGRES_HOST: db
#       POSTGRES_PORT: 5432
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: admin
#       POSTGRES_DATABASE: postgres
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#     ports:
#     - "5432:5432"
#     networks:
#       - webapp

#   pgadmin:
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#       PGADMIN_DEFAULT_PASSWORD: admin
#       PGADMIN_CONFIG_SERVER_MODE: 'False'
#     volumes:
#     - pgadmin:/root/.pgadmin
#     ports:
#       - "5050:80"
#     links:
#       - "db:psql-server"
#     networks:
#       - webapp

#   frontend:
#     image: node:17.0.1
#     command: npm run start:dev
#     volumes:
#      - ./frontend:/usr/src/app
#     working_dir: /usr/src/app
#     environment:
#       NODE_OPTIONS: --openssl-legacy-provider
#     ports:
#      - "3000:3000"
#     networks:
#       - webapp

#   backend:
#     image: node
#     command: npm run start:dev
#     volumes:
#     - ./backend:/usr/src/app
#     working_dir: /usr/src/app
#     ports:
#     - "5000:5000"
#     - "5001:5001"
#     - "5002:5002"
#     - "5003:5003"
#     depends_on:
#       - db
#     environment:
#      - CHOKIDAR_USEPOLLING=true
#     networks:
#     - webapp

# volumes:
#   db_data: {}
#   pgadmin: {}
  
# networks:
#   webapp:
#     driver: bridge
